library ieee;
use ieee.std_logic_1164.all;

entity DIGIDESTINED_SWITCH is
	PORT( 	EXP_DATA_AV: IN STD_LOGIC_VECTOR(N DOWNTO 0);
		EXP_DATA_ED: OUT STD_LOGIC_VECTOR(N DOWNTO 0);
		OUTPORT_DATA: OUT STD_LOGIC_VECTOR(N DOWNTO 0);
		EXP_DATA_AV: IN STD_LOGIC_VECTOR(N DOWNTO 0);
		EXP_DATA_RD: OUT STD_LOGIC_VECTOR(N DOWNTO 0);
		EXP_DATA: IN STD_LOGIC_VECTOR(N DOWNTO 0);
		BUF_DATA_AV: IN STD_LOGIC_VECTOR(N DOWNTO 0);
		BUF_DATA_OUT: OUT STD_LOGIC_VECTOR(N DOWNTO 0);
		BUF_DATA: IN STD_LOGIC_VECTOR(N DOWNTO 0);
		OUTPUT_PORT: OUT STD_LOGIC_VECTOR(7 DOWNTO 0);
		OUTPUT_PORT_VALID: OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
		CLK: IN STD_LOGIC;
		RST: 1 STD_LOGIC);
end DIGIDESTINED_SWITCH;

architecture ARCH_DIGIDESTINED_SWITCH of DIGIDESTINED_SWITCH is
NIL
NIL
begin
end ARCH_DIGIDESTINED_SWITCH;