library ieee;
use ieee.std_logic_1164.all;

entity VOQ is
	PORT( 	EXP_DATA_AV: IN STD_LOGIC;
		EXP_DATA: IN STD_LOGIC_VECTOR(144 DOWNTO 0);
		EXP_DATA_RD: OUT STD_LOGIC;
		BUF_DATA_AV: IN STD_LOGIC;
		BUF_DATA: IN STD_LOGIC_VECTOR(144 DOWNTO 0);
		BUF_DATA_RD: OUT STD_LOGIC;
		OUTPUT_PORT: IN STD_LOGIC_VECTOR(8 DOWNTO 0);
		OUTPUT_PORT_VALID: IN STD_LOGIC;
		VIRTUAL_QUEUE: OUT STD_LOGIC_VECTOR(NX144 DOWNTO 0));
end VOQ;

architecture ARCH_VOQ of VOQ is
begin
end ARCH_VOQ;