library ieee;
use ieee.std_logic_1164.all;

entity ARBITER is
	PORT( 	EXP_DATA: IN STD_LOGIC_VECTOR(NX144 DOWNTO 0);
		EXP_DATA_AV: IN STD_LOGIC_VECTOR(N DOWNTO 0);
		EXP_DATA_RD: OUT STD_LOGIC_VECTOR(N DOWNTO 0);
		BUF_DATA: IN STD_LOGIC_VECTOR(NX144 DOWNTO 0);
		BUF_DATA_AV: IN STD_LOGIC_VECTOR(N DOWNTO 0);
		BUF_DATA_RD: OUT STD_LOGIC_VECTOR(N DOWNTO 0);
		OUTPORT_DATA: OUT STD_LOGIC_VECTOR(144 DOWNTO 0);
		OUTPORT_DATA_AV: OUT STD_LOGIC;
		OUTPORT_DATA_RD: IN STD_LOGIC_VECTOR(1 DOWNTO 0));
end ARBITER;

architecture ARCH_ARBITER of ARBITER is
begin
end ARCH_ARBITER;